error: package directory 'my_package_py' does not exist
